name: Java Gradle CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Java-App
          path: app/build/libs/*.jar